# Generated by Django 6.0.3 on 2026-03-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("selected_column", models.CharField(blank=True, max_length=100)),
                ("total_rows", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando processamento"),
                            ("processing", "Processando"),
                            ("done", "Concluído"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("cep_original", models.CharField(max_length=20)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("found", models.BooleanField(default=False)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.uploadedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
    ]
