# Generated by Django 6.0.3 on 2026-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cepresult",
            name="latitude",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="cepresult",
            name="longitude",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
