# Generated by Django 6.0.3 on 2026-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cepresult_latitude_cepresult_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="cepresult",
            name="error_message",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
